CREATE TABLE XXBCM_INVOICES 
   (	INVOICE_ID NUMBER  CONSTRAINT XXBCM_INVOICES_PK PRIMARY KEY, 
	INVOICE_REFERENCE VARCHAR2(50), 
	INVOICE_DATE DATE, 
	INVOICE_STATUS VARCHAR2(50), 
	INVOICE_HOLD_REASON VARCHAR2(2000), 
	INVOICE_AMOUNT NUMBER(10,2), 
	INVOICE_DESCRIPTION VARCHAR2(2000), 
	ORDER_line_ID NUMBER, 
	 CHECK (INVOICE_STATUS IN ('Paid', 'Pending')) ENABLE, 
	 CONSTRAINT XXBCM_INVOICES_ORDER_FK FOREIGN KEY (ORDER_line_ID)
	  REFERENCES XXBCM_ORDERS_line (ORDER_line_ID) ENABLE
   ) ;

CREATE SEQUENCE SEQ_invoices
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE OR REPLACE TRIGGER increment_invoices_line_id_trigger
BEFORE INSERT ON XXBCM_INVOICES
FOR EACH ROW
BEGIN
    :NEW.INVOICE_id := SEQ_invoices.NEXTVAL;
END;