

	ALTER SESSION SET NLS_DATE_LANGUAGE = 'ENGLISH';
INSERT
	INTO
	XXBCM_SUPPLIERS
( SUPPLIER_NAME,
	SUPP_CONTACT_NAME,
	SUPP_ADDRESS,
	SUPP_CONTACT_1,
	SUPP_CONTACT_2,
	SUPP_EMAIL)
SELECT
	DISTINCT SUPPLIER_NAME ,
	SUPP_CONTACT_NAME,
	SUPP_ADDRESS,
	REPLACE(REPLACE((REGEXP_SUBSTR(convert_Contact(SUPP_CONTACT_NUMBER), '[^,]+', 1, 1)), ' ', ''), '.', '') AS contact1,
	REPLACE(REPLACE((REGEXP_SUBSTR(convert_Contact(SUPP_CONTACT_NUMBER), '[^,]+', 1, 2)), ' ', ''), '.', '') AS contact2,
	SUPP_EMAIL
FROM
	XXBCM_ORDER_MGT ;

	