
	ALTER SESSION SET NLS_DATE_LANGUAGE = 'ENGLISH';
INSERT INTO XXBCM_INVOICES (
  INVOICE_REFERENCE,
  INVOICE_DATE,
  INVOICE_STATUS,
  INVOICE_HOLD_REASON,
  INVOICE_AMOUNT,
  INVOICE_DESCRIPTION,
  ORDER_LINE_ID 
)
SELECT INVOICE_REFERENCE,
  preprocess_and_convert_to_date(INVOICE_DATE),
  INVOICE_STATUS,
  INVOICE_HOLD_REASON,
  convert_montant(INVOICE_AMOUNT),
  INVOICE_DESCRIPTION,
  (
	SELECT
		max(xs.ORDER_LINE_ID )
	FROM
		XXBCM_ORDER_LINE  xs
	WHERE
		xs.ORDER_LINE_REF = ord.order_ref
		)
 FROM XXBCM_ORDER_MGT ORD;

DELETE FROM XXBCM_INVOICES WHERE ORDER_LINE_ID IS NULL ;

