

	ALTER SESSION SET NLS_DATE_LANGUAGE = 'ENGLISH';
INSERT
	INTO
	XXBCM_SUPPLIERS
( SUPPLIER_NAME,
	SUPP_CONTACT_NAME,
	SUPP_ADDRESS,
	SUPP_CONTACT_1,
	SUPP_CONTACT_2,
	SUPP_EMAIL)
SELECT
	DISTINCT SUPPLIER_NAME ,
	SUPP_CONTACT_NAME,
	SUPP_ADDRESS,
	REPLACE(REPLACE((REGEXP_SUBSTR(convert_Contact(SUPP_CONTACT_NUMBER), '[^,]+', 1, 1)), ' ', ''), '.', '') AS contact1,
	REPLACE(REPLACE((REGEXP_SUBSTR(convert_Contact(SUPP_CONTACT_NUMBER), '[^,]+', 1, 2)), ' ', ''), '.', '') AS contact2,
	SUPP_EMAIL
FROM
	XXBCM_ORDER_MGT ;

-------order
INSERT
	INTO
	XXBCM_ORDERS
( ORDER_REF,
	order_date,
	ORDER_DESCRIPTION,
	ORDER_STATUS,
	ORDER_TOTAL_AMOUNT,
	SUPPLIER_ID)
SELECT
	ORDER_REF,
	preprocess_and_convert_to_date(order_date),
	ORDER_DESCRIPTION,
	ORDER_STATUS,
	convert_montant(ORDER_TOTAL_AMOUNT),
	(
	SELECT
		SUPPLIER_ID
	FROM
		XXBCM_SUPPLIERS xs
	WHERE
		xs.supplier_name = ord.supplier_name)
FROM
	XXBCM_ORDER_MGT ord
WHERE
	LENGTH (ORDER_REF)= 5
;
-------order_line

INSERT INTO XXBCM_ORDER_LINE
( ORDER_LINE_REF,ORDER_ID, ORDER_DESCRIPTION, ORDER_STATUS, ORDER_LINE_AMOUNT)
SELECT
    ord.order_ref,
	(
	SELECT
		order_id
	FROM
		XXBCM_ORDERS  xs
	WHERE
		xs.ORDER_REF= SUBSTR(ord.order_ref,1,5) ),
	ORDER_DESCRIPTION,
	ORDER_STATUS,
	convert_montant(ORDER_LINE_AMOUNT)
FROM
	XXBCM_ORDER_MGT ord
WHERE
	LENGTH (ORDER_REF) > 5
;


INSERT INTO XXBCM_INVOICES (
  INVOICE_REFERENCE,
  INVOICE_DATE,
  INVOICE_STATUS,
  INVOICE_HOLD_REASON,
  INVOICE_AMOUNT,
  INVOICE_DESCRIPTION,
  ORDER_LINE_ID 
)
SELECT INVOICE_REFERENCE,
  preprocess_and_convert_to_date(INVOICE_DATE),
  INVOICE_STATUS,
  INVOICE_HOLD_REASON,
  convert_montant(INVOICE_AMOUNT),
  INVOICE_DESCRIPTION,
  (
	SELECT
		max(xs.ORDER_LINE_ID )
	FROM
		XXBCM_ORDER_LINE  xs
	WHERE
		xs.ORDER_LINE_REF = ord.order_ref
		)
 FROM XXBCM_ORDER_MGT ORD;

DELETE FROM XXBCM_INVOICES WHERE ORDER_LINE_ID IS NULL ;

